backend:
   #name: test-repo
   name: git-gateway
   repo: "kierenfunk/mikal-howard"
   branch: main
media_folder: public/images
public_folder: images
publish_mode: editorial_workflow
collections:
  - name: "pages"
    label: "Pages"
    create: false
    editor:
      preview: true
    files:
      - label: "Home"
        name: "home"
        file: "src/markdown/home.md"
        fields:
          - label: "Summary"
            name: "summary"
            widget: markdown
          - label: "Selling Points"
            name: "selling_points"
            widget: list
            collapsed: true
            fields:
              - label: "Header"
                name: "header"
                widget: string 
              - label: "Body"
                name: "body"
                widget: markdown
          - label: "Testimonials"
            name: "testimonials"
            widget: list
            collapsed: true
            fields:
              - label: "Name of Person"
                name: "name"
                widget: string 
              - label: "Testimonial"
                name: "body"
                widget: markdown
          - label: "About"
            name: "home_about"
            widget: markdown
      - label: "About"
        name: "about"
        file: "src/markdown/about.md"
        fields:
          - label: "Header"
            name: "title"
            widget: string
          - label: "Our Mission"
            name: "mission"
            widget: markdown
          - label : "About Mikal"
            name: "about_mikal"
            widget: list
            collapse: true
            fields:
              - label: "Paragraph"
                name: "paragraph"
                widget: markdown
              - label: "Image"
                name: "image"
                required: false
                allow_multiple: false
                widget: image
      - label: "Privacy Policy"
        name: "privacy_policy"
        file: "src/markdown/privacy-policy.md"
        fields:
          - label: "Header"
            name: "title"
            widget: string
          - label: "Body"
            name: "body"
            widget: markdown
      - label: "Compliments & Concerns"
        name: "compliments_concerns"
        file: "src/markdown/compliments-concerns.md"
        fields:
          - label: "Header"
            name: "title"
            widget: string
          - label: "Body"
            name: "body"
            widget: markdown
  - name: "services"
    label: "Services"
    folder: "src/markdown/services"
    create: false
    fields:
      - label: "Slug"
        name: "slug"
        widget: string
      - label: "Service Name"
        name: "title"
        widget: string
      - label: "Logo"
        name: "logo"
        allow_multiple: false
        widget: image
      - name: "menu_summary"
        label: "Summary for the menu"
        widget: markdown
      - name: "home_summary"
        label: "Summary for the home page"
        widget: markdown
      - name: "body"
        label: "dunno what the layout is atm, but this is the main body"
        widget: markdown
      - name: "process"
        label: "Step by step process"
        widget: list
        fields:
          - label: "Body"
            name: "step_body"
            widget: markdown
          - label: "Header"
            name: "step_header"
            widget: string
      - name: "cta"
        label: "Something convincing"
        widget: markdown
